import { Theme } from "@/src/themes/ThemeContext";
import { StyleSheet } from "react-native";

const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      flex: 1,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.lg,
      paddingBottom: theme.spacing.xl,
    },
    listHeader: {
      width: "100%",
      gap: theme.spacing.md,
      paddingBottom: theme.spacing.md,
    },
    searchSection: {
      flexDirection: "row",
      alignItems: "center",
    },
    searchBar: {
      flex: 1,
    },
    filtersSection: {
      width: "100%",
      gap: theme.spacing.sm,
    },
    filterActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.spacing.sm,
    },
    filterButton: {
      width: 38,
      height: 38,
      borderRadius: theme.radius.full,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    filterButtonActive: {
      backgroundColor: theme.colors.primary,
    },
    filterChipsWrapper: {
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: theme.spacing.xs,
    },
    filterChip: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    filterChipText: {
      marginHorizontal: theme.spacing.xs,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    filterChipRemove: {
      marginLeft: theme.spacing.xs,
    },
    clearFiltersButton: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: theme.size.xs,
      borderRadius: theme.radius.full,
      paddingVertical: theme.spacing.xs,
      paddingHorizontal: theme.spacing.sm,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    clearFiltersText: {
      marginLeft: theme.spacing.xs,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
    },
    listContent: {
      paddingBottom: theme.spacing.xxl,
    },
    listSeparator: {
      height: theme.spacing.md,
    },
    card: {
      flexDirection: "row",
      alignItems: "flex-start",
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.xl,
      padding: theme.spacing.md,
      gap: theme.spacing.md,
    },
    cardImageWrapper: {
      width: 88,
      height: 88,
      borderRadius: theme.radius.lg,
      overflow: "hidden",
      // borderWidth: theme.size.xs,
      // borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    cardImage: {
      width: "100%",
      height: "100%",
    },
    cardImageFallback: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    cardContent: {
      flex: 1,
      gap: theme.spacing.sx,
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: theme.spacing.sm,
    },
    cardTitle: {
      flex: 1,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      fontWeight: "600",
    },
    cardCategory: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    cardStore: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
    },
    cardOriginalPrice: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
      textDecorationLine: "line-through",
    },
    cardPrice: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.primary,
      fontWeight: "700",
    },
    cardUnit: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    cardUnavailable: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
    },
    cardCode: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
    },
    feedbackWrapper: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: theme.spacing.lg,
      gap: theme.spacing.md,
      paddingVertical: theme.spacing.lg,
    },
    feedbackText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      textAlign: "center",
    },
    retryButton: {
      paddingHorizontal: theme.spacing.xl,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
      marginTop: theme.spacing.xs,
    },
    retryButtonText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
    },
    filterModalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.4)",
      justifyContent: "flex-end",
      alignItems: "center",
    },
    filterModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    filterModalCard: {
      width: "100%",
      maxHeight: "85%",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.xxl,
      paddingVertical: theme.spacing.lg,
      paddingHorizontal: theme.spacing.lg,
    },
    filterModalContent: {
      paddingBottom: theme.spacing.md,
    },
    filterModalTitle: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.gl,
      color: theme.colors.text,
      fontWeight: "600",
      textAlign: "center",
      marginBottom: theme.spacing.md,
    },
    filterCheckboxRow: {
      // marginTop: theme.spacing.md,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
    },
    filterCheckboxRowActive: {
      backgroundColor: theme.colors.primary,
    },
    filterCheckbox: {
      width: 20,
      height: 20,
      borderRadius: theme.radius.sm,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.sm,
      backgroundColor: theme.colors.surface,
    },
    filterCheckboxSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    filterCheckboxLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
    },
    filterCheckboxLabelActive: {
      color: theme.colors.onPrimary,
      fontWeight: "600",
    },
    favoriteFilterWrapper: {
      marginTop: theme.spacing.lg,
      marginBottom: theme.spacing.md,
      gap: theme.spacing.xs,
    },
    favoriteFilterTitle: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      fontWeight: "600",
      textDecorationLine: "underline",
    },
    favoriteTogglePill: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      borderRadius: theme.radius.full,
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
      backgroundColor: theme.colors.surface,
    },
    favoriteTogglePillActive: {
      backgroundColor: theme.colors.primary,
    },
    favoriteToggleCheckbox: {
      width: 22,
      height: 22,
      borderRadius: theme.radius.sm,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.sm,
      backgroundColor: theme.colors.surface,
    },
    favoriteToggleCheckboxActive: {
      backgroundColor: theme.colors.primary,
    },
    favoriteToggleLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
    },
    favoriteToggleLabelActive: {
      color: theme.colors.onPrimary,
      fontWeight: "600",
    },
    filterSection: {
      marginVertical: theme.spacing.lg,
    },
    filterSectionTitle: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      fontWeight: "regular",
      marginBottom: theme.spacing.sm,
      textDecorationLine: "underline"
    },
    categoriesGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: theme.spacing.sm,
    },
    categoryPill: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    categoryPillSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    categoryCheckbox: {
      width: 18,
      height: 18,
      borderRadius: theme.radius.sm,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.xs,
      backgroundColor: theme.colors.surface,
    },
    categoryCheckboxSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    categoryLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    categoryLabelSelected: {
      color: theme.colors.onPrimary,
      fontWeight: "600",
    },
    priceInputsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: theme.spacing.sm,
    },
    priceInputWrapper: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.lg,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
    },
    priceInputWrapperLast: {
      marginRight: 0,
    },
    priceInputLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      marginRight: theme.spacing.xs,
    },
    priceInput: {
      flex: 1,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
    },
    filterActions: {
      marginTop: theme.spacing.lg,
      gap: theme.spacing.sm,
    },
    applyFiltersButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.primary,
      borderRadius: theme.radius.full,
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
    },
    applyFiltersText: {
      marginLeft: theme.spacing.xs,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.onPrimary,
      fontWeight: "600",
    },
    cancelFiltersButton: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    cancelFiltersText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.primary,
      fontWeight: "600",
    },
    // Distance slider fallback (mirrors store styles)
    sliderFallback: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: theme.spacing.sm,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.xs,
    },
    sliderDisabled: {
      opacity: 0.5,
    },
    sliderFallbackButton: {
      width: 32,
      height: 32,
      borderRadius: theme.radius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.primary,
    },
    sliderFallbackButtonDisabled: {
      backgroundColor: theme.colors.disabled,
    },
    sliderFallbackButtonText: {
      color: theme.colors.onPrimary,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
    },
    sliderFallbackValue: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
    },
    sliderValueRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: theme.spacing.sm,
    },
    sliderValueUnlimited: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
    },
  });

export default createStyles;

