import { Theme } from "@/src/themes/ThemeContext";
import { StyleSheet } from "react-native";

const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      flex: 1,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.lg,
      paddingBottom: theme.spacing.xl,
    },
    listHeader: {
      width: "100%",
      gap: theme.spacing.md,
      paddingBottom: theme.spacing.md,
    },
    searchSection: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 0,
    },
    searchBar: {
      flex: 1,
    },
    filtersSection: {
      marginBottom: theme.spacing.sm,
      flexDirection: "column",
      alignItems: "stretch",
      width: "100%",
    },
    filterActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.spacing.sm,
      marginBottom: theme.spacing.sm,
    },
    filterButton: {
      width: 38,
      height: 38,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: theme.size.xs,
      marginRight: theme.spacing.ms,
      borderRadius: theme.radius.full,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    filterButtonActive: {
      backgroundColor: theme.colors.primary,
    },
    filterChipsWrapper: {
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: theme.spacing.xs,
    },
    filterChip: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.surface,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
    },
    filterChipText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      marginHorizontal: theme.spacing.xs,
    },
    filterChipRemove: {
      marginLeft: theme.spacing.xs,
    },
    clearFiltersWrapper: {
      marginLeft: theme.spacing.sx,
    },
    clearFiltersButton: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: theme.size.xs,
      marginRight: theme.spacing.sx,
      borderRadius: theme.radius.full,
      paddingVertical: theme.spacing.xs,
      borderColor: theme.colors.primary,
      paddingHorizontal: theme.spacing.sm,
      backgroundColor: theme.colors.surface,
    },
    clearFiltersText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
      marginLeft: theme.spacing.xs,
    },
    loadingWrapper: {
      paddingVertical: theme.spacing.lg,
      alignItems: "center",
      justifyContent: "center",
    },
    productsList: {
      flex: 1,
    },
    listContent: {
      paddingBottom: theme.spacing.xl,
    },
    productCard: {
      flexDirection: "row",
      alignItems: "flex-start",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.lg,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.md,
    },
    productImageWrapper: {
      width: 78,
      height: 78,
      borderRadius: theme.radius.md,
      backgroundColor: theme.colors.secondary,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    productImage: {
      width: "100%",
      height: "100%",
    },
    productFallbackImage: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    productInfo: {
      marginLeft: theme.spacing.md,
      flex: 1,
    },
    productInfoHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: theme.spacing.sm,
    },
    productFavoriteButton: {
      // borderWidth: theme.size.xs,
      // borderColor: theme.colors.primary,
      borderRadius: theme.radius.full,
      padding: theme.spacing.xs,
      backgroundColor: theme.colors.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    productName: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      marginBottom: theme.spacing.xs / 2,
      marginRight: theme.spacing.sm,
      flexShrink: 1,
    },
    productOriginalPrice: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
      textDecorationLine: "line-through",
    },
    productPrice: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.gl,
      color: theme.colors.primary,
      fontWeight: "700",
      marginTop: theme.spacing.xs,
    },
    productPriceUnavailable: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
      marginTop: theme.spacing.xs,
    },
    productUnit: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    productCode: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.disabled,
      marginTop: theme.spacing.xs,
    },
    emptyState: {
      paddingVertical: theme.spacing.xl,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyStateText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      textAlign: "center",
      marginBottom: theme.spacing.md,
    },
    retryButton: {
      paddingHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    retryButtonText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
    },
    filterModalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.4)",
      justifyContent: "flex-end",
      alignItems: "center",
      // paddingHorizontal: theme.spacing.lg,
    },
    filterModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    filterModalCard: {
      width: "100%",
      maxHeight: "85%",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.xxl,
      paddingVertical: theme.spacing.lg,
      paddingHorizontal: theme.spacing.lg,
    },
    filterModalContent: {
      paddingBottom: theme.spacing.md,
    },
    filterModalTitle: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.lg,
      color: theme.colors.text,
      fontWeight: "600",
      textAlign: "center",
    },
    filterCheckboxRow: {
      marginTop: theme.spacing.md,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
    },
    filterCheckboxRowActive: {
      backgroundColor: theme.colors.primary,
    },
    filterCheckbox: {
      width: 20,
      height: 20,
      borderRadius: theme.radius.sm,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.sm,
      backgroundColor: theme.colors.surface,
    },
    filterCheckboxSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    filterCheckboxLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.primary,
      fontWeight: "600",
    },
    filterCheckboxLabelActive: {
      color: theme.colors.onPrimary,
    },
    filterSection: {
      marginTop: theme.spacing.md,
      marginBottom: theme.spacing.md,
    },
    filterSectionTitle: {
      fontWeight: "600",
      marginBottom: theme.spacing.sm,
      color: theme.colors.text,
      fontSize: theme.fontSizes.md,
      fontFamily: theme.fonts.regular,
      textDecorationLine: "underline",
    },
    categoriesGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
    },
    categoryPill: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.surface,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.disabled,
      marginRight: theme.spacing.sm,
      marginBottom: theme.spacing.sm,
    },
    categoryPillSelected: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary,
    },
    categoryCheckbox: {
      width: 18,
      height: 18,
      borderRadius: theme.radius.sm,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
      marginRight: theme.spacing.xs,
    },
    categoryCheckboxSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    categoryLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    categoryLabelSelected: {
      color: theme.colors.onPrimary,
      fontWeight: "600",
    },
    priceInputsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    priceInputWrapper: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.lg,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      marginRight: theme.spacing.sm,
    },
    priceInputWrapperLast: {
      marginRight: 0,
      flexDirection: "row",
    },
    priceInputLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      marginBottom: theme.spacing.xs,
    },
    priceInput: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
    },
    filterActions: {
      marginTop: theme.spacing.lg,
      marginBottom: theme.spacing.sm,
    },
    applyFiltersButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.primary,
      borderRadius: theme.radius.full,
      paddingVertical: theme.spacing.md,
      paddingHorizontal: theme.spacing.md,
      marginBottom: theme.spacing.sm,
    },
    applyFiltersText: {
      marginLeft: theme.spacing.xs,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.onPrimary,
      fontWeight: "600",
    },
    cancelFiltersButton: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: theme.spacing.md,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    cancelFiltersText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.primary,
      fontWeight: "600",
    },
  });

export default createStyles;
