import { Theme } from "@/src/themes/ThemeContext";
import { StyleSheet } from "react-native";

const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    body: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    feedbackWrapper: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: theme.spacing.lg,
    },
    feedbackText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      textAlign: "center",
      marginTop: theme.spacing.sm,
    },
    retryButton: {
      marginTop: theme.spacing.md,
      paddingHorizontal: theme.spacing.xl,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    retryButtonText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
      fontWeight: "600",
    },
    scrollContent: {
      paddingHorizontal: theme.spacing.md,
      paddingTop: theme.spacing.md,
      paddingBottom: theme.spacing.xl,
    },
    masterToggle: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: theme.spacing.sx,
    },
    masterToggleText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      fontWeight: "600",
      marginLeft: theme.spacing.xs,
    },
    checkboxBase: {
      width: 20,
      height: 20,
      borderRadius: theme.radius.sm,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
    },
    checkboxChecked: {
      backgroundColor: theme.colors.primary,
    },
    storeCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.xl,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.border,
      marginTop: theme.spacing.sm,
      overflow: "hidden",
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    storeHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.sx,
      backgroundColor: theme.colors.surface,
    },
    storeHeaderText: {
      flex: 1,
      marginLeft: theme.spacing.sm,
    },
    storeTitle: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      fontWeight: "700",
    },
    storeSubtitle: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.disabled,
      marginTop: theme.spacing.sx,
    },
    productRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
      borderTopWidth: theme.size.xs,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    productSelector: {
      marginRight: theme.spacing.sm,
    },
    productCard: {
      flex: 1,
      flexDirection: "row",
      alignItems: "flex-start",
    },
    productDetails: {
      flexDirection: "row",
      flex: 1,
      paddingRight: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
    },
    productImageWrapper: {
      width: 56,
      height: 56,
      borderRadius: theme.radius.md,
      backgroundColor: theme.colors.secondary,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      marginRight: theme.spacing.xs,
    },
    productImage: {
      width: "100%",
      height: "100%",
    },
    productImageFallback: {
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      height: "100%",
    },
    productInfo: {
      flex: 1,
      paddingLeft: theme.spacing.sm,
    },
    productName: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      fontWeight: "600",
      marginBottom: theme.spacing.sx,
    },
    productOriginalPrice: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.disabled,
      textDecorationLine: "line-through",
      marginBottom: theme.spacing.sx,
    },
    removeButtonText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.primary,
      fontWeight: "600",
      marginBottom: theme.spacing.sx,
    },
    quantityWrapper: {
      marginTop: theme.spacing.xs,
    },
    quantityControls: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      borderRadius: theme.radius.full,
      paddingHorizontal: theme.spacing.sx,
      paddingVertical: theme.spacing.sx,
      alignSelf: "flex-start",
    },
    quantityButton: {
      padding: theme.spacing.sx,
    },
    quantityValue: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.primary,
      fontWeight: "600",
      marginHorizontal: theme.spacing.sx,
    },
    priceWrapper: {
      marginTop: theme.spacing.sm,
      alignItems: "flex-end",
    },
    productPrice: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      fontWeight: "bold",
      textAlign: "left",
    },
    shippingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.sx,
      backgroundColor: theme.colors.secondary,
      borderTopWidth: theme.size.xs,
      borderColor: theme.colors.border,
    },
    shippingLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.text,
    },
    shippingValue: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.text,
      fontWeight: "700",
    },
    shippingValueFree: {
      color: theme.colors.success,
    },
    summaryWrapper: {
      paddingHorizontal: theme.spacing.md,
      paddingTop: theme.spacing.sm,
      paddingBottom: theme.spacing.lg,
      backgroundColor: theme.colors.surface,
      borderTopWidth: theme.size.xs,
      borderColor: theme.colors.border,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 4,
    },
    summaryRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: theme.spacing.sx,
    },
    summaryLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.text,
    },
    summaryValue: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.text,
      fontWeight: "600",
    },
    summaryValueFree: {
      color: theme.colors.success,
    },
    summaryDivider: {
      height: theme.size.xs,
      backgroundColor: theme.colors.border,
      marginVertical: theme.spacing.sx,
    },
    summaryTotalLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      fontWeight: "600",
    },
    summaryTotalValue: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      fontWeight: "700",
    },
    checkoutButton: {
      marginTop: theme.spacing.md,
      backgroundColor: theme.colors.primary,
      borderRadius: theme.radius.full,
      paddingVertical: theme.spacing.sm,
      alignItems: "center",
      justifyContent: "center",
    },
    checkoutButtonDisabled: {
      opacity: theme.opacity.disabled,
    },
    checkoutButtonText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.onPrimary,
      fontWeight: "600",
    },
  });

export default createStyles;
