import { Theme } from "@/src/themes/ThemeContext";
import { StyleSheet } from "react-native";

const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    scrollContent: {
      paddingHorizontal: theme.spacing.lg,
      paddingBottom: theme.spacing.xl,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      borderBottomWidth: 2,
      padding: theme.spacing.lg,
      marginBottom: theme.spacing.lg,
      borderBottomColor: theme.colors.primary
    },
    searchBar: {
      flex: 1,
      marginRight: theme.spacing.sm,
    },
    notificationButton: {
      width: 44,
      height: 44,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
      backgroundColor: theme.colors.surface,
    },
    notificationBadge: {
      position: "absolute",
      top: -4,
      right: -2,
      minWidth: 18,
      height: 18,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: theme.spacing.sx,
    },
    notificationText: {
      color: theme.colors.onPrimary,
      fontSize: theme.fontSizes.xs,
      fontWeight: "600",
    },
    searchResultsWrapper: {
      position: "absolute",
      width: "98%",
      alignSelf: "center",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.xxl,
      borderWidth: 1,
      borderColor: theme.colors.primary,
      padding: theme.spacing.md,
      zIndex: 20,
      elevation: 6,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
    },
    searchResultsListContent: {
      paddingBottom: theme.spacing.sx,
    },
    searchResultCard: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: theme.spacing.sm,
    },
    searchResultCardSpacing: {
      marginBottom: theme.spacing.sm,
    },
    searchResultImageWrapper: {
      width: 48,
      height: 48,
      borderRadius: theme.radius.full,
      overflow: "hidden",
      marginRight: theme.spacing.sm,
      backgroundColor: theme.colors.secondary,
      alignItems: "center",
      justifyContent: "center",
    },
    searchResultImage: {
      width: "100%",
      height: "100%",
    },
    searchResultFallback: {
      flex: 1,
      width: "100%",
      height: "100%",
      alignItems: "center",
      justifyContent: "center",
    },
    searchResultInfo: {
      flex: 1,
      marginRight: theme.spacing.sm,
    },
    searchResultTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: theme.spacing.sx,
    },
    searchResultTitle: {
      flex: 1,
      fontSize: theme.fontSizes.md,
      fontWeight: "600",
      color: theme.colors.text,
      marginRight: theme.spacing.sm,
    },
    searchResultTag: {
      backgroundColor: theme.colors.secondary,
      borderRadius: theme.radius.full,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.sx,
    },
    searchResultTagText: {
      fontSize: theme.fontSizes.xs,
      color: theme.colors.primary,
      fontWeight: "600",
    },
    searchResultSubtitle: {
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    searchResultExtra: {
      fontSize: theme.fontSizes.xs,
      color: theme.colors.disabled,
      marginTop: theme.spacing.sx,
    },
    errorBanner: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.danger,
      padding: theme.spacing.md,
      borderRadius: theme.radius.lg,
      marginBottom: theme.spacing.lg,
    },
    errorText: {
      flex: 1,
      marginLeft: theme.spacing.sm,
      color: theme.colors.onPrimary,
      fontSize: theme.fontSizes.sm,
    },
    section: {
      marginBottom: theme.spacing.xl,
    },
    sectionTitle: {
      fontSize: theme.fontSizes.gl,
      fontWeight: "600",
      color: theme.colors.primary,
    },
    promotionCard: {
      flexDirection: "row",
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.primary,
      borderWidth: 1,
      borderRadius: theme.radius.xxl,
      padding: theme.spacing.md,
      marginTop: theme.spacing.md,
    },
    promotionImageWrapper: {
      width: 90,
      height: 90,
      borderRadius: theme.radius.lg,
      overflow: "hidden",
      marginRight: theme.spacing.md,
    },
    promotionImage: {
      width: "100%",
      height: "100%",
    },
    imageFallback: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.secondary,
      borderRadius: theme.radius.lg,
      padding: theme.spacing.sm,
    },
    promotionInfo: {
      flex: 1,
      justifyContent: "space-between",
    },
    promotionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: theme.spacing.xs,
    },
    promotionName: {
      flex: 1,
      fontSize: theme.fontSizes.md,
      fontWeight: "600",
      color: theme.colors.text,
      marginRight: theme.spacing.sm,
    },
    promotionFavoriteButton: {
      width: 32,
      height: 32,
      borderRadius: theme.radius.full,
      // borderWidth: 1,
      // borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    productSeller: {
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
      marginBottom: theme.spacing.sx,
    },
    originalPrice: {
      color: theme.colors.disabled,
      fontSize: theme.fontSizes.sm,
      textDecorationLine: "line-through",
    },
    currentPrice: {
      color: theme.colors.primary,
      fontSize: theme.fontSizes.gl,
      fontWeight: "600",
      marginTop: theme.spacing.sx,
    },
    unitLabel: {
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    unavailablePrice: {
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
      marginTop: theme.spacing.sx,
    },
    productCode: {
      marginTop: theme.spacing.sx,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.disabled,
    },
    sectionDivider: {
      height: 1,
      backgroundColor: theme.colors.border,
      marginBottom: theme.spacing.xl,
    },
    storeCard: {
      flexDirection: "row",
      alignItems: "flex-start",
      backgroundColor: theme.colors.surface,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      borderRadius: theme.radius.xl,
      padding: theme.spacing.md,
      marginTop: theme.spacing.md,
    },
    storeAvatar: {
      width: 58,
      height: 58,
      borderRadius: theme.radius.full,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.md,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.secondary,
    },
    storeAvatarImage: {
      width: "100%",
      height: "100%",
      borderRadius: theme.radius.full,
      resizeMode: "contain",
    },
    storeAvatarInitials: {
      fontSize: theme.fontSizes.sm,
      fontWeight: "700",
      color: theme.colors.primary,
    },
    storeDetails: {
      flex: 1,
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      columnGap: theme.spacing.sm,
      marginBottom: theme.spacing.xs,
    },
    storeName: {
      flex: 1,
      marginRight: theme.spacing.sm,
      fontSize: theme.fontSizes.gl,
      fontWeight: "600",
      color: theme.colors.text,
    },
    favoriteButton: {
      width: 32,
      height: 32,
      borderRadius: theme.radius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
    },
    statusBadge: {
      alignSelf: "flex-start",
      borderRadius: theme.radius.full,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      backgroundColor: theme.colors.danger,
      marginBottom: theme.spacing.xs,
    },
    statusBadgeText: {
      fontSize: theme.fontSizes.xs,
      color: theme.colors.onPrimary,
      fontWeight: "600",
    },
    metaRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: theme.spacing.xs,
      flexWrap: "wrap",
      gap: theme.spacing.xs,
    },
    metaItem: {
      flexDirection: "row",
      alignItems: "center",
    },
    metaText: {
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    metaTextWithIcon: {
      marginLeft: theme.spacing.xs,
    },
    metaSeparator: {
      width: 4,
      height: 4,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.disabled,
      marginHorizontal: theme.spacing.xs,
    },
    promoPill: {
      marginTop: theme.spacing.sm,
      alignSelf: "flex-start",
      backgroundColor: "#DFF6E2",
      borderRadius: theme.radius.full,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.xs,
      flexDirection: "row",
      alignItems: "center",
      columnGap: theme.spacing.xs,
    },
    promoText: {
      fontSize: theme.fontSizes.sm,
      color: theme.colors.success,
    },
    suggestionGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      marginTop: theme.spacing.md,
    },
    suggestionCard: {
      width: "30%",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: theme.spacing.sm,
      marginBottom: theme.spacing.md,
    },
    suggestionImageWrapper: {
      height: 80,
      alignItems: "center",
      justifyContent: "center",
    },
    suggestionImage: {
      width: "100%",
      height: "100%",
    },
    suggestionName: {
      marginTop: theme.spacing.sm,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    suggestionPrice: {
      marginTop: theme.spacing.sx,
      fontSize: theme.fontSizes.sm,
      fontWeight: "600",
      color: theme.colors.primary,
    },
    emptyText: {
      marginTop: theme.spacing.md,
      color: theme.colors.disabled,
      fontSize: theme.fontSizes.sm,
    },
    loadingText: {
      marginTop: theme.spacing.sm,
      color: theme.colors.text,
      fontSize: theme.fontSizes.sm,
    },
  });

export default createStyles;
