import { Theme } from "@/src/themes/ThemeContext";
import { StyleSheet } from "react-native";

const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    feedbackWrapper: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: theme.spacing.lg,
    },
    feedbackText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      textAlign: "center",
      marginTop: theme.spacing.md,
    },
    retryButton: {
      marginTop: theme.spacing.md,
      paddingHorizontal: theme.spacing.xl,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    retryButtonText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
    },
    scrollContent: {
      paddingHorizontal: theme.spacing.lg,
      paddingBottom: theme.spacing.xxl,
    },
    imageCarousel: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: theme.spacing.lg,
    },
    arrowButton: {
      width: 44,
      height: 44,
      borderRadius: theme.radius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
    },
    arrowButtonDisabled: {
      opacity: theme.opacity.disabled,
    },
    imageCard: {
      width: 220,
      height: 220,
      borderRadius: theme.radius.xxl,
      backgroundColor: theme.colors.surface,
      alignItems: "center",
      justifyContent: "center",
      marginHorizontal: theme.spacing.md,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 3,
    },
    productImage: {
      width: "100%",
      height: "100%",
      borderRadius: theme.radius.xxl,
    },
    productFallbackImage: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    dotsWrapper: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: theme.spacing.md,
    },
    dot: {
      width: 8,
      height: 8,
      borderRadius: theme.radius.full,
      marginHorizontal: theme.spacing.sx,
    },
    dotActive: {
      backgroundColor: theme.colors.primary,
    },
    dotInactive: {
      backgroundColor: theme.colors.disabled,
      opacity: 0.4,
    },
    informationSection: {
      marginTop: theme.spacing.xl,
    },
    productName: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xl,
      color: theme.colors.text,
      fontWeight: "600",
    },
    productOriginalPrice: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.disabled,
      marginTop: theme.spacing.sm,
      textDecorationLine: "line-through",
    },
    productPrice: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xl,
      color: theme.colors.primary,
      fontWeight: "700",
      marginTop: theme.spacing.xs,
    },
    productUnit: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    productUnavailable: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.disabled,
      marginTop: theme.spacing.xs,
    },
    metaInfo: {
      marginTop: theme.spacing.md,
    },
    metaInfoText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
      marginBottom: theme.spacing.xs,
    },
    metaInfoLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
      fontWeight: "bold",
    },
    quantitySection: {
      marginTop: theme.spacing.xl,
      alignItems: "center",
      justifyContent: "center",
    },
    quantityLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      marginBottom: theme.spacing.sm,
    },
    quantityControls: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      width: 160,
    },
    quantityButton: {
      width: 36,
      height: 36,
      borderRadius: theme.radius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.secondary,
    },
    quantityButtonDisabled: {
      opacity: theme.opacity.disabled,
    },
    quantityValue: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.lg,
      color: theme.colors.text,
      fontWeight: "600",
    },
    actionsSection: {
      marginTop: theme.spacing.xl,
    },
    addToCartButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.primary,
      paddingVertical: theme.spacing.md,
      borderRadius: theme.radius.full,
      marginBottom: theme.spacing.sm,
    },
    addToCartText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.onPrimary,
      fontWeight: "600",
      marginLeft: theme.spacing.sm,
    },
    buyNowButton: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: theme.spacing.md,
      borderRadius: theme.radius.full,
      backgroundColor: "#FF4D4D",
    },
    buyNowText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.onPrimary,
      fontWeight: "600",
    },
    descriptionSection: {
      marginTop: theme.spacing.xl,
    },
    descriptionTitle: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.gl,
      color: theme.colors.text,
      fontWeight: "600",
      marginBottom: theme.spacing.sm,
    },
    descriptionText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      lineHeight: 20,
    },
  });

export default createStyles;
