import { Theme } from "@/src/themes/ThemeContext";
import { StyleSheet } from "react-native";

const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    contentContainer: {
      paddingBottom: theme.spacing.xxl,
    },
    bannerWrapper: {
      position: "relative",
      width: "100%",
      height: 210,
    },
    bannerImage: {
      width: "100%",
      height: "100%",
      justifyContent: "flex-end",
      overflow: "hidden",
      borderBottomLeftRadius: theme.radius.xl,
      borderBottomRightRadius: theme.radius.xl,
    },
    bannerOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.35)",
    },
    backButton: {
      position: "absolute",
      top: theme.spacing.xl,
      left: theme.spacing.lg,
      width: 40,
      height: 40,
      borderRadius: theme.radius.full,
      // borderWidth: theme.size.xs,
      // borderColor: "rgba(255,255,255,0.6)",
      backgroundColor: "rgba(0,0,0,0.35)",
      alignItems: "center",
      justifyContent: "center",
    },
    summaryCard: {
      marginTop: -theme.spacing.xl,
      marginHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.xxl,
      paddingBottom: theme.spacing.lg,
      paddingHorizontal: theme.spacing.lg,
      borderRadius: theme.radius.xl,
      backgroundColor: theme.colors.surface,
      alignItems: "center",
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.15,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 14,
      elevation: 6,
    },
    logoWrapper: {
      position: "absolute",
      top: -45,
      width: 90,
      height: 90,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    logo: {
      width: "100%",
      height: "100%",
      resizeMode: "contain",
    },
    favoriteButton: {
      position: "absolute",
      top: theme.spacing.md,
      right: theme.spacing.md,
      width: 42,
      height: 42,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
    },
    favoriteButtonActive: {
      backgroundColor: theme.colors.primary,
    },
    storeName: {
      marginTop: theme.spacing.xl,
      fontFamily: theme.fonts.regular,
      fontWeight: "700",
      fontSize: theme.fontSizes.lg,
      color: theme.colors.text,
      textAlign: "center",
    },
    metaRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.spacing.xs,
      marginTop: theme.spacing.sm,
    },
    metaItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.spacing.xs,
    },
    metaText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    metaSeparator: {
      width: 4,
      height: 4,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.disabled,
    },
    summaryPromo: {
      marginTop: theme.spacing.md,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.radius.full,
      backgroundColor: "#DFF6E2",
      flexDirection: "row",
      alignItems: "center",
      gap: theme.spacing.xs,
    },
    summaryPromoText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.success,
    },
    section: {
      marginTop: theme.spacing.xl,
      paddingHorizontal: theme.spacing.lg,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    sectionTitle: {
      fontFamily: theme.fonts.regular,
      fontWeight: "700",
      fontSize: theme.fontSizes.gl,
      color: theme.colors.text,
    },
    sectionText: {
      marginTop: theme.spacing.sm,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      lineHeight: 20,
    },
    sectionLinkWrapper: {
      paddingVertical: theme.spacing.xs,
      paddingHorizontal: theme.spacing.sm,
    },
    sectionLink: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
    },
    infoRow: {
      flexDirection: "row",
      gap: theme.spacing.lg,
      marginTop: theme.spacing.sm,
    },
    infoColumn: {
      flex: 1,
    },
    infoItem: {
      marginBottom: theme.spacing.sm,
    },
    infoLabel: {
      fontFamily: theme.fonts.regular,
      fontWeight: "700",
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    infoValue: {
      marginTop: theme.spacing.xs,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      lineHeight: 18,
    },
    promoCarousel: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: theme.spacing.md,
    },
    carouselArrow: {
      width: 38,
      height: 38,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
    },
    promoList: {
      paddingHorizontal: theme.spacing.sm,
      gap: theme.spacing.sm,
    },
    promoCard: {
      width: 170,
      borderRadius: theme.radius.lg,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
      padding: theme.spacing.sm,
      alignItems: "center",
    },
    promoImage: {
      width: 100,
      height: 100,
      resizeMode: "contain",
    },
    promoName: {
      marginTop: theme.spacing.sm,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      textAlign: "center",
    },
    promoOriginal: {
      marginTop: theme.spacing.xs,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.disabled,
      textDecorationLine: "line-through",
    },
    promoPrice: {
      marginTop: theme.spacing.xs,
      fontFamily: theme.fonts.regular,
      fontWeight: "700",
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
      textAlign: "center",
    },
    promoUnit: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.disabled,
    },
    footerLinkWrapper: {
      marginTop: theme.spacing.xl,
      marginHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.md,
      borderTopWidth: theme.size.xs,
      borderTopColor: theme.colors.border,
      alignItems: "center",
    },
    footerLink: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
      textAlign: "center",
    },
    notFoundContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: theme.spacing.lg,
    },
    notFoundText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      textAlign: "center",
      marginBottom: theme.spacing.lg,
    },
    notFoundButton: {
      paddingHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.radius.lg,
      backgroundColor: theme.colors.primary,
    },
    notFoundButtonText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.onPrimary,
    },
  });

export default createStyles;
