import { Theme } from "@/src/themes/ThemeContext";
import { StyleSheet } from "react-native";

const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    content: {
      flex: 1,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.lg,
    },
    listHeader: {
      width: "100%",
      gap: theme.spacing.md,
      paddingBottom: theme.spacing.md,
    },
    searchRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: theme.spacing.md,
    },
    metaSeparator: {
      width: 4,
      height: 4,
      marginHorizontal: theme.spacing.sm,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.disabled,
    },
    locationRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: theme.spacing.lg,
    },
    filterShortcut: {
      width: 38,
      height: 38,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.sm,
    },
    filterShortcutActive: {
      backgroundColor: theme.colors.primary,
    },
    filtersSection: {
      width: "100%",
      gap: theme.spacing.sm,
    },
    filterActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.spacing.sm,
    },
    filterChipsWrapper: {
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: theme.spacing.xs,
    },
    filterChip: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    filterChipText: {
      marginHorizontal: theme.spacing.xs,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    filterChipRemove: {
      marginLeft: theme.spacing.xs,
    },
    clearFiltersButton: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: theme.size.xs,
      borderRadius: theme.radius.full,
      paddingVertical: theme.spacing.xs,
      paddingHorizontal: theme.spacing.sm,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
    },
    clearFiltersText: {
      marginLeft: theme.spacing.xs,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
    },
    filterChipGhost: {
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    filterChipGhostText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
    },
    listContent: {
      paddingBottom: theme.spacing.xxl,
    },
    listContentEmpty: {
      flexGrow: 1,
      justifyContent: "flex-start",
    },
    storeCard: {
      flexDirection: "row",
      alignItems: "flex-start",
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.lg,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.md,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
    },
    storeAvatar: {
      width: 58,
      height: 58,
      borderRadius: theme.radius.full,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.md,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
    },
    storeLogo: {
      width: "100%",
      height: "100%",
      borderRadius: theme.radius.full,
      overflow: "hidden",
      resizeMode: "contain",
    },
    avatarInitials: {
      fontFamily: theme.fonts.regular,
      fontWeight: "700",
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
    },
    storeDetails: {
      flex: 1,
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: theme.spacing.xs,
    },
    storeName: {
      flex: 1,
      marginRight: theme.spacing.sm,
      fontFamily: theme.fonts.regular,
      fontWeight: "light",
      fontSize: theme.fontSizes.lg,
      color: theme.colors.text,
    },
    favoriteButton: {
      width: 34,
      height: 34,
      // borderRadius: theme.radius.full,
      // borderWidth: theme.size.xs,
      // borderColor: theme.colors.primary,
      // backgroundColor: theme.colors.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    // favoriteButtonActive: {
    //   backgroundColor: theme.colors.primary,
    // },
    statusBadge: {
      alignSelf: "flex-start",
      borderRadius: theme.radius.full,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      backgroundColor: theme.colors.danger,
      marginBottom: theme.spacing.xs,
    },
    statusBadgeText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.xs,
      color: theme.colors.onPrimary,
    },
    storeDescription: {
      marginTop: theme.spacing.xs,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    metaRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: theme.spacing.xs,
      flexWrap: "wrap",
    },
    metaItem: {
      flexDirection: "row",
      alignItems: "center",
      marginRight: theme.spacing.xs,
    },
    metaText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    metaTextWithIcon: {
      marginLeft: theme.spacing.xs,
    },
    metaDivider: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
      marginHorizontal: theme.spacing.xs,
    },
    promoPill: {
      marginTop: theme.spacing.sm,
      alignSelf: "flex-start",
      backgroundColor: "#DFF6E2",
      borderRadius: theme.radius.full,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.xs,
      flexDirection: "row",
      alignItems: "center",
    },
    promoText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.success,
    },
    slider: {
      width: "100%",
      marginTop: theme.spacing.sm,
    },
    sliderFallback: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: theme.spacing.sm,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.xs,
    },
    sliderDisabled: {
      opacity: 0.5,
    },
    sliderFallbackButton: {
      width: 32,
      height: 32,
      borderRadius: theme.radius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.primary,
    },
    sliderFallbackButtonDisabled: {
      backgroundColor: theme.colors.disabled,
    },
    sliderFallbackButtonText: {
      color: theme.colors.onPrimary,
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
    },
    sliderFallbackValue: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
    },
    sliderValueRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: theme.spacing.sm,
    },
    sliderValueBox: {
      minWidth: 50,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.radius.sm,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.xs,
    },
    sliderValueText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
    },
    sliderValueSuffix: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    sliderValueUnlimited: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.disabled,
    },
    emptyState: {
      alignItems: "center",
      marginTop: theme.spacing.lg,
    },
    emptyStateIcon: {
      marginBottom: theme.spacing.sm,
      justifyContent: "center",
      alignItems: "center",
    },
    emptyStateText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.disabled,
      textAlign: "center",
    },
    filterModalContainer: {
      flex: 1,
      justifyContent: "flex-end",
    },
    filterModalOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.25)",
    },
    filterModalCard: {
      backgroundColor: theme.colors.surface,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.lg,
      paddingBottom: theme.spacing.xl,
      borderTopLeftRadius: theme.radius.xl,
      borderTopRightRadius: theme.radius.xl,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.25,
      shadowOffset: { width: 0, height: -2 },
      shadowRadius: 10,
      elevation: 10,
    },
    filterModalHandle: {
      alignSelf: "center",
      width: 56,
      height: 4,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.disabled,
      marginBottom: theme.spacing.lg,
    },
    filterModalTitle: {
      textAlign: "center",
      fontFamily: theme.fonts.regular,
      fontWeight: "700",
      fontSize: theme.fontSizes.lg,
      color: theme.colors.text,
      marginBottom: theme.spacing.lg,
    },
    filterFieldGroup: {
      marginBottom: theme.spacing.lg,
    },
    radiusHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    filterLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      fontWeight: "700",
      textDecorationLine: "underline",
      color: theme.colors.text,
      marginBottom: theme.spacing.xs,
    },
    filterFieldInput: {
      backgroundColor: theme.colors.secondary,
      borderRadius: theme.radius.lg,
      borderWidth: 0,
      color: theme.colors.text,
      paddingVertical: theme.spacing.sm,
    },
    filterOptionRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: theme.spacing.xs,
      marginTop: theme.spacing.sm,
    },
    filterOptionBadge: {
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.xs,
      borderRadius: theme.radius.full,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    filterOptionBadgeActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary,
    },
    filterOptionText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    filterOptionTextActive: {
      color: theme.colors.onPrimary,
    },
    favoriteFilterTitle: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.text,
      fontWeight: "700",
      marginBottom: theme.spacing.sm,
      textDecorationLine: "underline",
    },
    favoriteTogglePill: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      borderRadius: theme.radius.full,
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
      backgroundColor: theme.colors.surface,
    },
    favoriteTogglePillActive: {
      backgroundColor: theme.colors.primary,
    },
    favoriteToggleCheckbox: {
      width: 24,
      height: 24,
      borderRadius: theme.radius.sm,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      marginRight: theme.spacing.sm,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
    },
    favoriteToggleCheckboxActive: {
      backgroundColor: theme.colors.primary,
    },
    favoriteToggleLabel: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.text,
    },
    favoriteToggleLabelActive: {
      color: theme.colors.onPrimary,
    },
    radiusToggle: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.spacing.xs,
    },
    radiusToggleText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.sm,
      color: theme.colors.primary,
    },
    applyFilterButton: {
      marginTop: theme.spacing.sm,
    },
    cancelFilterButton: {
      marginTop: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.radius.lg,
      borderWidth: theme.size.xs,
      borderColor: theme.colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    cancelFilterButtonText: {
      fontFamily: theme.fonts.regular,
      fontSize: theme.fontSizes.md,
      color: theme.colors.primary,
    },
  });

export default createStyles;
